<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>ValidationEntryPoint</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../BuoyCalc.Windows.csproj" />
  </ItemGroup>
</Project>
