$ErrorActionPreference = "Stop"

param(
    [string]$OutputPath = "docs/REPORT_STORE_CONSUMER_MAP.generated.md"
)

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$outputFullPath = Join-Path $repoRoot $OutputPath

function Get-RelativePath([string]$path) {
    return [System.IO.Path]::GetRelativePath($repoRoot, $path).Replace("\\", "/")
}

$sourceFiles = @(
    Get-ChildItem -Path $repoRoot -Recurse -File -Filter "*.cs" |
        Where-Object {
            $_.FullName -notmatch "[\\/]bin[\\/]" -and
            $_.FullName -notmatch "[\\/]obj[\\/]"
        }
)

if ($sourceFiles.Count -eq 0) {
    throw "No C# source files found."
}

$storeSymbols = @(
    "MooringShapeStore",
    "MooringIterativeSolverStore"
)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Report store consumer map")
$lines.Add("")
$lines.Add("Generated by `tools/write-report-store-consumer-map.ps1`.")
$lines.Add("")
$lines.Add("This file maps report-store declarations and references from the checked-out source tree.")
$lines.Add("")
$lines.Add("It is an architecture-audit aid only. It does not define calculation physics or application behavior.")
$lines.Add("")

foreach ($storeSymbol in $storeSymbols) {
    $references = @(
        Select-String -Path $sourceFiles.FullName -SimpleMatch $storeSymbol
    )

    if ($references.Count -eq 0) {
        throw "No references found for $storeSymbol."
    }

    $escapedSymbol = [regex]::Escape($storeSymbol)
    $declarationPattern = "\b(class|record)\s+" + $escapedSymbol + "\b"
    $setPattern = $escapedSymbol + "\.Set\s*\("
    $readPattern = $escapedSymbol + "\.(Get|TryGet|Current)\b"

    $declarations = @(
        $references | Where-Object { $_.Line -match $declarationPattern }
    )

    $writeReferences = @(
        $references | Where-Object { $_.Line -match $setPattern }
    )

    $readCandidates = @(
        $references | Where-Object {
            $_.Line -notmatch $declarationPattern -and
            $_.Line -notmatch $setPattern
        }
    )

    $explicitReads = @(
        $references | Where-Object { $_.Line -match $readPattern }
    )

    $lines.Add("## " + $storeSymbol)
    $lines.Add("")
    $lines.Add("| Metric | Count |")
    $lines.Add("|---|---:|")
    $lines.Add("| Total references | " + $references.Count + " |")
    $lines.Add("| Declarations | " + $declarations.Count + " |")
    $lines.Add("| Write references | " + $writeReferences.Count + " |")
    $lines.Add("| Read candidates | " + $readCandidates.Count + " |")
    $lines.Add("| Explicit reads | " + $explicitReads.Count + " |")
    $lines.Add("")

    if ($declarations.Count -gt 0) {
        $lines.Add("### Declarations")
        $lines.Add("")
        foreach ($item in $declarations) {
            $lines.Add("- `" + (Get-RelativePath $item.Path) + ":" + $item.LineNumber + "`")
        }
        $lines.Add("")
    }

    $lines.Add("### References")
    $lines.Add("")
    foreach ($item in $references) {
        $lines.Add("- `" + (Get-RelativePath $item.Path) + ":" + $item.LineNumber + "` — `" + $item.Line.Trim().Replace("`", "``") + "`")
    }
    $lines.Add("")
}

$outputDirectory = Split-Path -Parent $outputFullPath
if (-not (Test-Path $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory | Out-Null
}

$lines | Set-Content -Path $outputFullPath -Encoding UTF8
Write-Host ("Report store consumer map written to " + (Get-RelativePath $outputFullPath))
